# DATA 
datarawdirectory: data/raw/
datainterimdirectory: data/interim/
dataprocesseddirectory: data/processed/
datacalculationsdirectory: data/calculations/
dataname: export_all_tables
mri_dataname: mri
genetic_name: genetic
implants: implanty
genetic_dataname_all: DFNB1_1620
genetic_dataname: DFNB1_2025-10-10
mapping: anon_mapping
resultsdirectory: results/

patients_sheetname: "Pacjenci"

# Names of Excel sheets containing audiometry data
audiometry_names:
  - "Audiometria_Tonalna"
  - "Audiometria_Slowna"
  - "Audiometria_Pole_Swobodne"

# Mapping of sheet names to short keys used in the code
audiometry_map:
  Audiometria_Tonalna: "tonal"
  Audiometria_Slowna: "verbal"
  Audiometria_Pole_Swobodne: "free_field"

# Columns to be dropped when reading audiometry data
audiometry_dropcolumns:
  - "WYNIKI_POZOSTALE"
  - "WYKONUJACY_BADANIE"
  - "OPIS_BADANIA"
  - "id"

# Columns used for matching patient data; these will not be renamed
match_columns:
  - "NUMER_HISTORII_CHOROBY"
  - "NUMER_W_JEDNOSTCE"

tonaldataname: audiometry_tonal
verbaldataname: audiometry_verbal
freefielddataname: audiometry_free_field

#tonal audiometry columns
date_column: "DATA_BADANIA"
description_columnname: "OPIS_BADANIA"
audiometry_name_columnname: "NAZWA_AUDIOMETRII"
audiometry_earside_columnname: "UWAGI_DO_AUDIOMETRII"
audiometry_type_columnname: "TYP_AUDIOMETRII"
patient_number_columnname: "NUMER_HISTORII_CHOROBY"
pesel_columnname: "PESEL"

#implants columns
patient_identifier_columnname: "PATID"
age_of_occurence_columnname: "WIEK_WYSTAPIENIA"
age_of_recognition_columnname: "WIEK_ROZPOZNANIA"
implant_date_columnname: "1_IMPLANT_SLIMAKOWY_DATA_WSZCZEPIENIA"
implant_ear_columnname: "1_IMPLANT_SLIMAKOWY_UCHO"
second_implant_date_columnname: "2_IMPLANT_SLIMAKOWY_DATA WSZCZEPIENIA"
second_implant_ear_columnname: "2_IMPLANT_SLIMAKOWY_UCHO"

mask_merging_columns:
  - "NUMER_HISTORII_CHOROBY"
  - "UWAGI_DO_AUDIOMETRII"

bone_audiometry: ["BoneMask", "Bone"]
air_audiometry: ["AirMask", "Air"]
vibro_audiometry: ['VibroMask', 'Vibro']


pta_columns:
  PTA2:
    - WYNIK_X_500
    - WYNIK_X_1000
    - WYNIK_X_2000
  PTA4:
    - WYNIK_X_500
    - WYNIK_X_1000
    - WYNIK_X_2000
    - WYNIK_X_4000
  hfPTA:
    - WYNIK_X_4000
    - WYNIK_X_8000
    
columns_to_fill:
  - WYNIK_X_125
  - WYNIK_X_250
  - WYNIK_X_500
  - WYNIK_X_750
  - WYNIK_X_1000
  - WYNIK_X_1500
  - WYNIK_X_2000
  - WYNIK_X_3000
  - WYNIK_X_4000
  - WYNIK_X_6000
  - WYNIK_X_8000

first_symmetry_columns:
  - WYNIK_X_125
  - WYNIK_X_250
  - WYNIK_X_500
  - WYNIK_X_750
  - WYNIK_X_1000
  - WYNIK_X_1500
  - WYNIK_X_2000
  - WYNIK_X_3000
  - WYNIK_X_4000
  - WYNIK_X_6000
  - WYNIK_X_8000

second_symmetry_columns:
  - WYNIK_X_2000
  - WYNIK_X_3000
  - WYNIK_X_4000
  - WYNIK_X_6000
  - WYNIK_X_8000

filling_limit: 110

threshold_def1: 20
threshold_def2: 15

biap_hearing_levels:
  - { max: 20, label: "Prawidlowy" }
  - { max: 40, label: "Lekki" }
  - { max: 70, label: "Umiarkowany" }
  - { max: 90, label: "Znaczny" }
  - { max: 150, label: "Gleboki" }

asha_hearing_levels:
  - { max: 15, label: "Prawidlowy" }
  - { max: 25, label: "Nieznaczny" }
  - { max: 40, label: "Lekki" }
  - { max: 55, label: "Umiarkowany" }
  - { max: 70, label: "Umiarkowanie_ciezki" }
  - { max: 90, label: "Znaczny" }
  - { max: 150, label: "Gleboki" }

#hearing loss type
pta_threshold: 20

bone_all_mean_columns:
  - "WYNIK_X_500"
  - "WYNIK_X_1000"
  - "WYNIK_X_2000"
  - "WYNIK_X_4000"

bone_hf_all_mean_columns:
  - "WYNIK_X_4000"
  - "WYNIK_X_6000"

first_opt_columns:
  - "WYNIK_X_250"
  - "WYNIK_X_500"
  - "WYNIK_X_1000"
  - "WYNIK_X_2000"
first_opt_threshold: 10
first_opt_how_many: 3

second_opt_columns:
  - "WYNIK_X_250"
  - "WYNIK_X_500"
  - "WYNIK_X_1000"
  - "WYNIK_X_2000"
  - "WYNIK_X_4000"

hearing_loss_criteria:
  Sluch_prawidlowy:
    air:
      PTA4_condition: 1
      REZERWA: 0
    bone:
      bone_mean_condition: 1

  Niedosluch_przewodzeniowy:
    air:
      PTA4_condition: 0
      REZERWA: 1
    bone:
      bone_mean_condition: 1

  Niedosluch_odbiorczy_1:
    air:
      PTA4_condition: 0
      REZERWA: 0
    bone:
      bone_mean_condition: 0

  Niedosluch_odbiorczy_2:
    air:
      hfPTA_condition: 0
      REZERWA: 0
    bone:
      bone_mean_condition_hf: 0
    
  Niedosluch_odbiorczy_3:
    air:
      PTA4_condition: 0
      REZERWA: 0
    vibro:
      bone_mean_condition: 0

  Niedosluch_odbiorczy_4:
    air:
      hfPTA_condition: 0
      REZERWA: 0
    vibro:
      bone_mean_condition_hf: 0

  Niedosluch_mieszany:
    air:
      PTA4_condition: 0
      REZERWA: 1
    bone:
      bone_mean_condition: 0

Datasets:
  prawidlowy:
    - "Prawidlowy"
    - "Prawidlowy"

  gleboki:
    - "Gleboki"
    - "Gleboki"
  
  znaczny:
    - "Znaczny"
    - "Znaczny"

  lekki:
    - "Lekki"
    - "Lekki"

  umiarkowany:
    - "Umiarkowany"
    - "Umiarkowany"

  

